apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  selector:
    matchLabels:
      run: notification
  replicas: 1
  template:
    metadata:
        labels:
            run: notification
    spec:
      containers:
      - name: notification-service
        image: wbira/notification:latest