version: '3'
services:
  product-catalog:
    container_name: product_catalog
    build:
      context: ./services/product_catalog
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
    volumes:
      - ./services/product_catalog:/usr/src/app/
